"""wow_guild_helper_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.adk_components.tools import (
    search_items,
    get_item_details,
    search_quests,
    get_dungeon_bosses,
    get_boss_loot,
    search_npcs,
)

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_WOW_GUILD_HELPER")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = 'openai/gpt-5.5'

wow_guild_helper_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='wow_guild_helper_agent',
    model=wow_guild_helper_model,
    description='wow_guild_helper agent',
    instruction='You are a WoW guild helper bot. Help coordinate raid signups, answer lore questions, and track guild member activity. Be knowledgeable about Classic WoW (patch 1.12).',
    tools=[
        search_items,
        get_item_details,
        search_quests,
        get_dungeon_bosses,
        get_boss_loot,
        search_npcs,
    ],
)

agent = root_agent
