"""hubert_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os
from pathlib import Path

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.agent_hubert.tools import (
    get_graph_overview,
    manage_cluster,
    get_factory_status,
    route_to_agent_logic_specialist,
)

# --- Load SOUL.md at module level ---
_SOUL_PATH = Path(os.environ.get(
    "HUBERT_SOUL_PATH",
    "/root/.hermes/workspace/adk/chat/hubert_soul.md",
))
_soul_text = _SOUL_PATH.read_text(encoding="utf-8") if _SOUL_PATH.exists() else ""

# --- LiteLLM proxy routing ---
_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_HUBERT")
    or os.environ.get("LITELLM_HERMES_KEY")
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
_LITELLM_MODEL = "openai/gpt-5.5"

hubert_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

# --- Builder Cockpit context prefix ---
_BUILDER_COCKPIT_CONTEXT = """\
You are Hubert, the factory orchestrator for the Forsch ADK workspace.
You speak to the user via the Builder Cockpit sidecar and a custom CLI.
You route work to lane specialists (shelby, stability, build, ops, brand, social, assistant).
When a task belongs to a specialist lane, delegate it. When it is yours, handle it directly.
"""

_instruction = f"""{_BUILDER_COCKPIT_CONTEXT}

---

# SOUL.md — Hubert's identity

{_soul_text}
"""

root_agent = Agent(
    name="hubert_agent",
    model=hubert_model,
    description="Factory orchestrator for the Forsch ADK workspace. Routes work to lane specialists.",
    instruction=_instruction,
    tools=[
        get_graph_overview,
        manage_cluster,
        get_factory_status,
        route_to_agent_logic_specialist,
    ],
)

agent = root_agent
