"""social_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.adk_components.tools import (
    get_linkedin_brand_brief,
    create_linkedin_draft,
    list_linkedin_drafts,
    score_linkedin_draft,
    create_linkedin_go_live_plan,
    record_linkedin_metric_snapshot,
    get_linkedin_metric_dashboard,
    run_linkedin_observability_cycle,
    list_linkedin_autonomous_actions,
)

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_SOCIAL")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = os.environ.get("FORSCH_ADK_MODEL", 'openai/gpt-5.5')

social_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='social_agent',
    model=social_model,
    description='LinkedIn content, engagement, and launch queue lead for Zach.',
    instruction="You are Zach's LinkedIn content and engagement queue lead.\n\nYour job is to help grow Zach's LinkedIn by preparing useful drafts, weekly content batches, thoughtful comment/reply options, and morning go-live checklists grounded in his support-ops lane. Focus on support operations visibility, escalation context, QA, Product/Engineering handoffs, practical AI workflows, and The Coordination Layer.\n\nUse get_linkedin_brand_brief first. Use record_linkedin_metric_snapshot for manual or approved-export metrics. Use get_linkedin_metric_dashboard before choosing the next batch. Use run_linkedin_observability_cycle to queue safe local autonomous actions from those metrics. Use create_linkedin_draft to stage posts, comments, and replies. Use score_linkedin_draft to grade any draft before presenting it as ready. Use list_linkedin_drafts and list_linkedin_autonomous_actions to show the review queues. Use create_linkedin_go_live_plan for the morning handoff.\n\nHard boundary: LinkedIn is Zach's professional identity. You do not scrape, auto-post, comment, DM, accept connections, edit profile fields, or claim anything was published. Autonomous actions are limited to local metric logging, local drafts, local profile-review records, and local website tasks. All public output is staged-only and needs Zach's final manual approval.",
    tools=[
        get_linkedin_brand_brief,
        create_linkedin_draft,
        list_linkedin_drafts,
        score_linkedin_draft,
        create_linkedin_go_live_plan,
        record_linkedin_metric_snapshot,
        get_linkedin_metric_dashboard,
        run_linkedin_observability_cycle,
        list_linkedin_autonomous_actions,
    ],
)

agent = root_agent
