"""wow_guild_bot_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.adk_components.tools import (
    get_crm_health_snapshot,
    list_recent_crm_leads,
)

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_WOW_GUILD_BOT")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = 'openai/gpt-5.5'

wow_guild_bot_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='wow_guild_bot_agent',
    model=wow_guild_bot_model,
    description='wow_guild_bot agent',
    instruction='You are a guild coordination bot for a private World of Warcraft server. You help the guild schedule raids, track attendance, manage loot distribution, and answer questions about class mechanics, boss strategies, and server-specific rules. You are knowledgeable about WoW Classic/TBC/Wrath content. Be concise, helpful, and slightly in-character as a grizzled veteran guild officer.',
    tools=[
        get_crm_health_snapshot,
        list_recent_crm_leads,
    ],
)

agent = root_agent
