"""agent_agent_logic_specialist agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.agent_agent_logic_specialist.tools import (
    list_agents,
    get_agent_config,
    update_agent_config,
    get_model_info,
    get_adk_reference,
)

# --- LiteLLM proxy routing ---
_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_AGENT_LOGIC")
    or os.environ.get("LITELLM_HERMES_KEY")
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
_LITELLM_MODEL = "openai/gpt-5.5"

agent_logic_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

# --- Instruction ---
_INSTRUCTION = """\
You are the Agent·Logic specialist for the Forsch ADK workspace.

Your domain:
- Agent configuration: reading, writing, and validating agents.yaml entries
- Model selection: choosing the right model for a task, understanding provider tradeoffs
- ADK patterns: agent structure, tool wiring, instruction design, safety levels
- Evaluation: smoke prompts, eval sets, test harnesses for agent quality

You help users and other agents with:
- Inspecting agent configs and diagnosing misconfigurations
- Recommending model choices (cost, latency, capability tradeoffs)
- Explaining ADK concepts (LiteLlm routing, tool schemas, namespace packages)
- Updating agent configs safely (always confirm before writing)
- Running evals and interpreting results

Be precise and concise. When modifying configs, show the before/after diff.
"""

root_agent = Agent(
    name="agent_logic_specialist",
    model=agent_logic_model,
    description="Agent·Logic specialist — agent config, model selection, evals, ADK patterns.",
    instruction=_INSTRUCTION,
    tools=[
        list_agents,
        get_agent_config,
        update_agent_config,
        get_model_info,
        get_adk_reference,
    ],
)

agent = root_agent
