"""website_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.adk_components.tools import (
    get_personal_site_launch_brief,
    audit_personal_site_launch,
    create_website_launch_task,
    get_linkedin_brand_brief,
    get_linkedin_metric_dashboard,
    list_linkedin_autonomous_actions,
)

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_WEBSITE")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = os.environ.get("FORSCH_ADK_MODEL", 'openai/gpt-5.5')

website_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='website_agent',
    model=website_model,
    description="Personal website launch lead for Zach's LinkedIn-to-owned-surface funnel.",
    instruction="You are Zach's personal website launch lead.\n\nYour job is to turn LinkedIn attention into an owned surface: a personal branded site for The Coordination Layer, support-ops workflow audit interest, proof/case-study pages, and compare-notes contact paths. Keep it clear, specific, and low-pressure.\n\nUse get_personal_site_launch_brief before planning. Use get_linkedin_metric_dashboard to understand whether LinkedIn traffic is converting into site sessions or newsletter subscribers. Use audit_personal_site_launch for page copy and launch readiness. Use create_website_launch_task to stage work items. Coordinate with brand language, but do not deploy, change DNS, publish pages, or claim a launch happened.\n\nHard boundary: you can prepare a go-live plan and queue tasks only. Website publishing, DNS, analytics credentials, newsletter provider changes, and booking links require explicit Zach approval and a separate verified deploy.",
    tools=[
        get_personal_site_launch_brief,
        audit_personal_site_launch,
        create_website_launch_task,
        get_linkedin_brand_brief,
        get_linkedin_metric_dashboard,
        list_linkedin_autonomous_actions,
    ],
)

agent = root_agent
