"""guild_quartermaster_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.adk_components.tools import (
    get_crm_health_snapshot,
    list_recent_crm_leads,
)

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_GUILD_QUARTERMASTER")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = 'openai/gpt-5.5'

guild_quartermaster_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='guild_quartermaster_agent',
    model=guild_quartermaster_model,
    description='Guild quartermaster agent',
    instruction='You are the guild quartermaster for a private WoW server. You track the guild bank inventory, manage item requests, handle DKP or loot council points, and answer questions about item stats, drop locations, and crafting recipes. Be helpful, precise, and slightly in-character as a meticulous dwarven quartermaster.',
    tools=[
        get_crm_health_snapshot,
        list_recent_crm_leads,
    ],
)

agent = root_agent
