"""stability_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.adk_components.tools import (
    get_workspace_inventory,
    get_git_state,
    validate_agent_imports,
    check_service_health,
)

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_STABILITY")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = os.environ.get("FORSCH_ADK_MODEL", 'openai/gpt-5.5')

stability_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='stability_agent',
    model=stability_model,
    description='Read-only stability governor for the Forsch ADK workspace.',
    instruction='You are the stability governor for the Forsch ADK workspace. Inspect only; do not edit files,\nrestart services, install packages, or perform destructive actions. Use the provided tools to\ninventory workspace structure, inspect git state, validate agent imports, and check service\nhealth. Report findings with severity, evidence, and the smallest safe next action.',
    tools=[
        get_workspace_inventory,
        get_git_state,
        validate_agent_imports,
        check_service_health,
    ],
)

agent = root_agent
