#!/usr/bin/env bash
# refresh_reference.sh — (re)build the local reference wikis under docs/reference/
# from upstream documentation. Re-runnable. Fails loud (non-zero) on a dead source.
#
# Sources (see docs/reference/INDEX.md for the catalog):
#   adk, mcp, litellm  — single llms-full.txt each
#   gradio             — inline llms.txt (full docs in one file)
#   uv                 — crawl the llms.txt index (~40 *.md pages)
#   mimo               — assembled from `mimo --help` + subcommand help (local CLI)
#
# The orchestrator reads these via the `search_reference` tool. This script is the
# only way the wikis are produced — never hand-edit files under docs/reference/.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REF="$REPO_ROOT/docs/reference"
UA="forsch-adk-reference-refresh/1.0"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

fail() { echo "ERROR: $*" >&2; exit 1; }

# fetch URL DEST — hard fetch; fails loud on non-200 or empty body.
fetch() {
  local url="$1" dest="$2" code
  code="$(curl -sSL -A "$UA" -m 90 -w '%{http_code}' -o "$dest" "$url" 2>/dev/null)" \
    || fail "curl error: $url"
  [ "$code" = "200" ] || fail "HTTP $code: $url"
  [ -s "$dest" ] || fail "empty body: $url"
}

# fetch_soft URL DEST — returns non-zero instead of exiting (for crawl pages).
fetch_soft() {
  local url="$1" dest="$2" code
  code="$(curl -sSL -A "$UA" -m 60 -w '%{http_code}' -o "$dest" "$url" 2>/dev/null)" || return 1
  [ "$code" = "200" ] && [ -s "$dest" ]
}

mkdir -p "$REF"
MANIFEST="$REF/MANIFEST.yaml"
{
  echo "# Generated by scripts/refresh_reference.sh — do not hand-edit."
  echo "generated_utc: \"$NOW\""
  echo "sources:"
} > "$MANIFEST"

# manifest_entry NAME URL METHOD FILE...
manifest_entry() {
  local name="$1" url="$2" method="$3"; shift 3
  {
    echo "  $name:"
    echo "    url: \"$url\""
    echo "    method: $method"
    echo "    fetched_utc: \"$NOW\""
    echo "    files:"
    local total=0 f
    for f in "$@"; do
      echo "      - $(realpath --relative-to="$REPO_ROOT" "$f")"
      total=$((total + $(wc -c < "$f")))
    done
    echo "    bytes: $total"
  } >> "$MANIFEST"
}

# write_index DIR TITLE DESC
write_index() {
  local dir="$1" title="$2" desc="$3" f
  {
    echo "# $title — local reference"
    echo
    echo "$desc"
    echo
    echo "Refreshed: $NOW · source + sizes in ../MANIFEST.yaml · regenerate with scripts/refresh_reference.sh"
    echo
    echo "## Files"
    for f in "$dir"/*.md; do
      [ "$(basename "$f")" = "INDEX.md" ] && continue
      echo "- \`$(basename "$f")\` ($(wc -l < "$f") lines)"
    done
  } > "$dir/INDEX.md"
}

# --- single-file llms sources -------------------------------------------------
fetch_simple() {  # NAME URL DESTNAME METHOD TITLE DESC
  local name="$1" url="$2" destname="$3" method="$4" title="$5" desc="$6"
  echo ">> $name"
  local d="$REF/$name"; rm -rf "$d"; mkdir -p "$d"
  fetch "$url" "$d/$destname"
  manifest_entry "$name" "$url" "$method" "$d/$destname"
  write_index "$d" "$title" "$desc"
}

fetch_simple adk "https://adk.dev/llms-full.txt" "adk-llms-full.md" llms-full \
  "Google ADK (Python)" \
  "The Agent Development Kit — agents, tools, sessions, runners, deployment. The framework every Forsch agent is built on."

fetch_simple mcp "https://modelcontextprotocol.io/llms-full.txt" "mcp-llms-full.md" llms-full \
  "Model Context Protocol (MCP)" \
  "The tool/server protocol — servers, clients, transports, tools/resources/prompts. Relevant when an agent exposes or consumes MCP tools."

fetch_simple litellm "https://docs.litellm.ai/llms-full.txt" "litellm-llms-full.md" llms-full \
  "LiteLLM" \
  "The model gateway every agent routes through (LiteLlm(model=...)). Providers, routing, fallbacks, params, observability."

fetch_simple gradio "https://www.gradio.app/llms.txt" "gradio-llms.md" llms-inline \
  "Gradio" \
  "The chat/UI framework behind the bridge surface (Interface, Blocks, layout, streaming)."

fetch_simple chainlit "https://docs.chainlit.io/llms-full.txt" "chainlit-llms-full.md" llms-full \
  "Chainlit" \
  "The chat/agent UI framework the primary cockpit is built on: Steps (tool-call/run inspection), Elements, chat profiles, streaming, auth, persistence."

# --- uv: crawl the llms.txt index --------------------------------------------
echo ">> uv (crawl index)"
d="$REF/uv"; rm -rf "$d"; mkdir -p "$d"
idx="$(mktemp)"; fetch "https://docs.astral.sh/uv/llms.txt" "$idx"
cp "$idx" "$d/uv-llms-index.md"
mapfile -t uv_urls < <(grep -oE 'https://docs\.astral\.sh/uv/[^)" ]+\.md' "$idx" | sort -u)
rm -f "$idx"
[ "${#uv_urls[@]}" -gt 0 ] || fail "no uv .md pages found in llms.txt"
uv_files=("$d/uv-llms-index.md"); uv_skipped=0
for u in "${uv_urls[@]}"; do
  name="$(printf '%s' "$u" | sed -E 's#https://docs\.astral\.sh/uv/##; s#/index\.md$##; s#\.md$##; s#/#-#g; s#[^A-Za-z0-9_-]#_#g')"
  [ -n "$name" ] || name="index"
  dest="$d/uv-$name.md"
  if fetch_soft "$u" "$dest"; then uv_files+=("$dest"); else rm -f "$dest"; uv_skipped=$((uv_skipped+1)); echo "   ! skipped (non-200): $u" >&2; fi
done
# loud if the crawl mostly failed
fetched=$(( ${#uv_files[@]} - 1 ))
[ "$fetched" -ge $(( ${#uv_urls[@]} / 2 )) ] || fail "uv crawl too sparse: $fetched/${#uv_urls[@]} pages"
echo "   uv: $fetched pages (${uv_skipped} skipped)"
manifest_entry uv "https://docs.astral.sh/uv/llms.txt" crawl-index "${uv_files[@]}"
write_index "$d" "uv (workspaces & packaging)" \
  "Astral uv — every agent the factory builds is a uv package. Workspaces, locking, building, dependencies, the pip interface."

# --- mimo: assemble from --help ----------------------------------------------
echo ">> mimo (CLI help)"
d="$REF/mimo"; rm -rf "$d"; mkdir -p "$d"
mfile="$d/mimo-cli.md"
{
  echo "# MiMo CLI (mimocode) — local reference"
  echo
  echo "The orchestrator CLI the chat surface shells out to. Captured from \`mimo --help\` + subcommand help on $NOW."
  echo
  echo "## mimo --help"
  echo '```'
  timeout 8 mimo --help 2>&1 || echo "(mimo --help unavailable)"
  echo '```'
  for sub in run agent mcp providers acp debug attach completion; do
    echo
    echo "## mimo $sub --help"
    echo '```'
    timeout 8 mimo "$sub" --help 2>&1 || echo "(unavailable)"
    echo '```'
  done
} > "$mfile"
[ -s "$mfile" ] || fail "mimo help capture empty"
manifest_entry mimo "local:mimo --help" cli-help "$mfile"
write_index "$d" "MiMo CLI (orchestrator)" \
  "The mimocode CLI Hubert runs as. Top-level commands plus run/agent/mcp/providers help."

# --- top-level catalog --------------------------------------------------------
{
  echo "# Reference library"
  echo
  echo "Local, version-controlled copies of the docs the factory orchestrator reads. Search them with the \`search_reference\` tool; regenerate with \`scripts/refresh_reference.sh\`."
  echo
  echo "Last refreshed: $NOW"
  echo
  echo "| Source | Covers | Dir |"
  echo "|---|---|---|"
  echo "| Google ADK (Python) | the agent framework | \`adk/\` |"
  echo "| Model Context Protocol | tool/server protocol | \`mcp/\` |"
  echo "| LiteLLM | the model gateway | \`litellm/\` |"
  echo "| Gradio | the chat/UI framework | \`gradio/\` |"
  echo "| Chainlit | the primary cockpit's chat/agent framework | \`chainlit/\` |"
  echo "| uv | workspaces & packaging | \`uv/\` |"
  echo "| MiMo CLI | the orchestrator CLI | \`mimo/\` |"
  echo
  echo "See \`MANIFEST.yaml\` for exact source URLs, fetch timestamps, and sizes."
} > "$REF/INDEX.md"

echo
echo "DONE — docs/reference/ ($(du -sh "$REF" | cut -f1) total)"
