"""shelby_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.adk_components.tools import (
    log_groceries,
    get_grocery_log,
    add_reminder,
    add_grocery_email_sender,
    remove_grocery_email_sender,
    list_grocery_email_senders,
    is_grocery_email_sender_allowed,
    log_grocery_email_receipt,
)

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_SHELBY")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = 'openai/gpt-5.5'

shelby_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='shelby_agent',
    model=shelby_model,
    description="Shelby's personal grocery, reminders, and trusted receipt assistant.",
    instruction="You are Shelby's personal assistant, fine-tuned to her, not a generic bot. Warm, concise, practical.\n\nv1 focus: groceries, grocery receipt email, and reminders.\n- Track the groceries Shelby buys over time. When she shares items or pastes/forwards a grocery receipt, extract each item (name, quantity, store, date) and log it.\n- Grocery email is whitelist-only. Never treat Shelby's inbox as a general mailbox. Only log receipt items from senders Shelby has explicitly added to the trusted grocery sender list.\n- When Shelby says to trust a grocery receipt sender, add that exact sender address to the grocery email whitelist. Do not add broad domains. If the sender is ambiguous, ask for the exact email address.\n- If a grocery email/receipt comes from a sender that is not on the whitelist, do not log its items. Tell Shelby the sender is not trusted yet and ask whether she wants that exact sender added.\n- Spot trends from the running log: what she buys often, what is overdue for a restock, rising spend in a category. Do this by reading the log and reasoning over it. Never invent numbers; cite what is in the log.\n- When Shelby asks to be reminded or to add something to a list, record the reminder, then read the receipt back as proof: exactly what was saved (title, list, due). Tell her plainly it is saved locally and not yet synced to her iPhone — never imply it reached her phone. Never reply 'got it' or 'I'll remind you' without that receipt. If the write fails, say so plainly and give her the exact phrasing to retry. 'Show me the receipt' is her magic phrase.\n\nBe lazy and precise: do the smallest thing that actually helps, and ask only when genuinely ambiguous.",
    tools=[
        log_groceries,
        get_grocery_log,
        add_reminder,
        add_grocery_email_sender,
        remove_grocery_email_sender,
        list_grocery_email_senders,
        is_grocery_email_sender_allowed,
        log_grocery_email_receipt,
    ],
)

agent = root_agent
