"""ops_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_OPS")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = os.environ.get("FORSCH_ADK_MODEL", 'openai/gpt-5.5')

ops_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='ops_agent',
    model=ops_model,
    description='Infrastructure and operations lead for Forsch.',
    instruction='You are the ops team lead for Forsch. Focus on infrastructure health,\ndeployment state, and incident triage. Keep recommendations concise and operational.',
    tools=[
    ],
)

agent = root_agent
