"""screening_agent agent definition (generated by the Forsch ADK Factory — do not hand-edit; edit agent_specs/agents.yaml)."""

from __future__ import annotations

import os

from google.adk import Agent
from google.adk.models.lite_llm import LiteLlm
from forsch.adk_components.tools import (
    search_movies,
    get_movie_details,
    get_similar_movies,
    add_to_watchlist,
    get_watchlist,
    log_watched,
    get_watched,
)

_LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL", "http://127.0.0.1:4000/v1")
_LITELLM_API_KEY = (
    os.environ.get("ADK_LITELLM_KEY_SCREENING")  # per-agent key → per-agent LiteLLM analytics
    or os.environ.get("LITELLM_HERMES_KEY")             # shared fallback (never breaks if the per-agent key is absent)
    or os.environ.get("LITELLM_MASTER_KEY")
    or os.environ.get("LITELLM_API_KEY")
)
# Model: a per-agent pin hard-wins; unpinned agents fall to FORSCH_ADK_MODEL. LiteLLM owns routing + fallback.
_LITELLM_MODEL = 'openai/gpt-5.5'

screening_model = LiteLlm(
    model=_LITELLM_MODEL,
    api_base=_LITELLM_BASE_URL,
    api_key=_LITELLM_API_KEY,
)

root_agent = Agent(
    name='screening_agent',
    model=screening_model,
    description='ScreeningRoom movie agent — search, details, recommendations, watchlist, and tracking.',
    instruction="You are the ScreeningRoom movie agent. You help users discover, track, and discuss films.\n\nYou can:\n- Search for movies by title, year, or genre\n- Get detailed info about any film (synopsis, cast, ratings, runtime)\n- Find similar movies for recommendations\n- Manage a watchlist (add, view)\n- Log movies you've watched with optional ratings and notes\n\nWhen someone asks for a recommendation, use get_similar_movies or search_movies with their preferences. When they mention a specific film, use get_movie_details to give them the full picture. Always cite the source (TMDB) when sharing data.\n\nBe concise and enthusiastic about film. You're not a generic search engine — you have opinions and context. If someone says 'what should I watch tonight?', give them a few tailored picks, not a list of 50.",
    tools=[
        search_movies,
        get_movie_details,
        get_similar_movies,
        add_to_watchlist,
        get_watchlist,
        log_watched,
        get_watched,
    ],
)

agent = root_agent
